version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: .
      dockerfile: Dockerfile.filebeat
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    volumes:
      - ./logs:/src/logs
    depends_on:
      - elasticsearch
      - kibana

  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-app
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
    volumes:
      - ./logs:/source/logs
      - ./uploads:/source/uploads

volumes:
  elasticsearch_data:
    driver: local
